# Next iteration of a config file
# Replaces 'config.txt' AND 'event.txt'
#
# Syntax
# YAML syntax
#
# Following are configuration examples of 
# different types of inputs.
# 
# FullyDefined:
#   event: AN_EVENT
#   event2: UN_EVENT
#   type: encoder
#   clk: 17
#   dt: 24
#   step: 1
#   value:
#     payload: heavy
#
# AnalogInp:
#   event: SET_THROTTLE
#   type: analog
#   channel: 0
#   threshold: 0.01
#   decimals: 9
#   min_clip: 0.00245
#   max_clip: 0.998
#   trigger: 12             # Pin defining the enable
#   offset: 
#   maximum: 



##################
## GENERAL SETUP #
##################

General:
  type: config            # config
  cycle: 0.001            # Recommended 0.001
  station: WEAPONS   # HELM, ENGINEERING, SCIENCE
  udp_ip: 192.168.1.255
  udp_port: 41114

##############
## FIRE TUBE #
##############

FireButton0:
  event: FIRE_TUBE
  type: push_button
  pin: 100
  invert: True
  value:
    tubeId: 0

FireButton1:
  event: FIRE_TUBE
  type: push_button
  pin: 101
  invert: True
  value:
    tubeId: 1

FireButto2:
  event: FIRE_TUBE
  type: push_button
  pin: 102
  invert: True
  value:
    tubeId: 2

FireButton3:
  event: FIRE_TUBE
  type: push_button
  pin: 103
  invert: True
  value:
    tubeId: 3

FireButton4:
  event: FIRE_TUBE
  type: push_button
  pin: 104
  invert: True
  value:
    tubeId: 4

FireButton5:
  event: FIRE_TUBE
  type: push_button
  pin: 105
  invert: True
  value:
    tubeId: 5

FireButton6:
  event: FIRE_TUBE
  type: push_button
  pin: 106
  invert: True
  value:
    tubeId: 6

FireButton7:
  event: FIRE_TUBE
  type: push_button
  pin: 107
  invert: True
  value:
    tubeId: 7


##############
## LOAD TUBE #
##############


LoadButton7:
  event: LOAD_OR_UNLOAD_TUBE
  type: push_button
  pin: 108
  invert: True
  value:
    tubeId: 7

LoadButton6:
  event: LOAD_OR_UNLOAD_TUBE
  type: push_button
  pin: 109
  invert: True
  value:
    tubeId: 6

LoadButton5:
  event: LOAD_OR_UNLOAD_TUBE
  type: push_button
  pin: 110
  invert: True
  value:
    tubeId: 5

LoadButton4:
  event: LOAD_OR_UNLOAD_TUBE
  type: push_button
  pin: 111
  invert: True
  value:
    tubeId: 4

LoadButton3:
  event: LOAD_OR_UNLOAD_TUBE
  type: push_button
  pin: 112
  invert: True
  value:
    tubeId: 3

LoadButton2:
  event: LOAD_OR_UNLOAD_TUBE
  type: push_button
  pin: 113
  invert: True
  value:
    tubeId: 2

LoadButton1:
  event: LOAD_OR_UNLOAD_TUBE
  type: push_button
  pin: 114
  invert: True
  value:
    tubeId: 1

LoadButton0:
  event: LOAD_OR_UNLOAD_TUBE
  type: push_button
  pin: 115
  invert: True
  value:
    tubeId: 0


##################
## CHOOSE WEAPON #
##################


SetHoming:
  event: SELECT_WEAPON
  type: push_button
  pin: 14
  invert: True
  value:
    value: HOMING

SetNuke:
  event: SELECT_WEAPON
  type: push_button
  pin: 15
  invert: True
  value:
    value: NUKE

SetMine:
  event: SELECT_WEAPON
  type: push_button
  pin: 23
  invert: True
  value:
    value: MINE

SetEMP:
  event: SELECT_WEAPON
  type: push_button
  pin: 24
  invert: True
  value:
    value: EMP

SetHVLI:
  event: SELECT_WEAPON
  type: push_button
  pin: 7
  invert: True
  value:
    value: HVLI


##############
## other stuff
##############


Calibrate:
  event: CALIBRATE_SHIELDS
  type: push_button
  pin: 26
  invert: True

SwitchShields:
  event: SHIELDS_UP
  event2: SHIELDS_DOWN
  type: switch
  pin: 16
  invert: True

SwitchTarget:
  event: AUTOMATIC_TARGETING
  event2: MANUAL_TARGETING
  type: switch
  pin: 20
  invert: True

SwitchsSelfDestruct:
  event: CONFIRM_SELF_DESTRUCT
  event2: REVOKE_CONFIRM_SELF_DESTRUCT
  type: switch
  pin: 21
  invert: True


#############
## ENCODERS #
#############


# DUAL PURPOSE ENCODER \/

TargetEncoder0a:
  event: MISSILE_TARGET_ANGLE
  type: encoder
  clk: 27
  dt: 22

  step: 1

TargetEncoder0b:
  event: TARGET_NEXT_ENEMY
  event2: TARGET_PREVIOUS_ENEMY
  type: encoder
  clk: 27
  dt: 22
  step: -10 # optional

# DUAL PURPOSE ENCODER /\


ShieldEncoder:
  event: SET_SHIELD_FREQUENCY
  type: encoder
  clk: 29
  dt: 31
  step: 1

BeamEncoder:
  event: SET_BEAM_FREQUENCY
  type: encoder
  clk: 33
  dt: 35
  step: 1


###########
## ANALOG #
###########

# requres tuning before use

AnalogBeamTarget:
  event: SET_BEAM_TARGET_NUMERIC
  type: analog
  channel: 0
  threshold: 0.1
  min_clip: 0
  max_clip: 1
  trigger: 0


# EOF
