# Next iteration of a config file
# Replaces 'config.txt' AND 'event.txt'
#
# Syntax
# YAML syntax
#
# Following are configuration examples of
# different types of inputs.
#
# FullyDefined:
#   event: AN_EVENT
#   event2: UN_EVENT
#   type: encoder
#   clk: 17
#   dt: 24
#   step: 1
#   value:
#     payload: heavy
#
# AnalogInp:
#   event: SET_THROTTLE
#   type: analog
#   channel: 0
#   threshold: 0.01
#   decimals: 9
#   min_clip: 0.00245
#   max_clip: 0.998
#   trigger: 12             # Pin defining the enable
#   offset:
#   maximum:



##################
## GENERAL SETUP #
##################

General:
  type: config            # config
  cycle: 0.001            # Recommended 0.001
  station: ENGINEER-B   # HELM, ENGINEERING, SCIENCE
  udp_ip: 192.168.1.255
  udp_port: 41114


#############
## BUTTONS ##
#############

# None

###########
## ANALOG #
###########

# requres tuning before use

AnalogImpulsePower:
  event: SET_IMPULSE_ENGINES_POWER
  type: analog
  channel: 10
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 300
  trigger: 0

AnalogImpulseCoolant:
  event: SET_IMPULSE_ENGINES_COOLANT
  type: analog
  channel: 11
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 100
  trigger: 0

## JUMP / WARP DUAL EVENT

AnalogJumpPower:
  event: SET_JUMP_DRIVE_POWER
  type: analog
  channel: 12
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 300
  trigger: 0

AnalogJumpCoolant:
  event: SET_JUMP_DRIVE_COOLANT
  type: analog
  channel: 13
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 100
  trigger: 0

#SET_WARP_DRIVE_POWER

AnalogWarpPower:
  event: SET_WARP_DRIVE_POWER
  type: analog
  channel: 12
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 300
  trigger: 0

AnalogWarpCoolant:
  event: SET_REAR_SHIELD_GENERATOR_COOLANT
  type: analog
  channel: 13
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 100
  trigger: 0

## SHIELDS

AnalogFShieldPower:
  event: SET_FRONT_SHIELD_GENERATOR_POWER
  type: analog
  channel: 14
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 300
  trigger: 0


AnalogFShieldCoolant:
  event: SET_FRONT_SHIELD_GENERATOR_COOLANT
  type: analog
  channel: 15
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 100
  trigger: 0


AnalogRShieldPower:
  event: SET_REAR_SHIELD_GENERATOR_POWER
  type: analog
  channel: 16
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 300
  trigger: 0


AnalogRShieldCoolant:
  event: SET_REAR_SHIELD_GENERATOR_COOLANT
  type: analog
  channel: 17
  threshold: 0.1
  min_clip: 0
  max_clip: 1023
  min: 0
  max: 100
  trigger: 0

