name: HwDriver2

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Build for Raspberry Pi Zero 1
      env:
        GOOS: linux
        GOARCH: arm
        GOARM: 6
      run: cd HwDriver2; go build -v -o hwdriver2-rpi-zero1 cmd/hwdriver2/main.go

    - name: Build for Raspberry Pi Zero 2
      env:
        GOOS: linux
        GOARCH: arm
        GOARM: 7
      run: cd HwDriver2; go build -v -o hwdriver2-rpi-zero2 cmd/hwdriver2/main.go

    - name: Archive artifacts - Zero 1
      uses: actions/upload-artifact@v4
      with:
        name: hwdriver2-zero1
        path: HwDriver2/hwdriver2-rpi-zero1

    - name: Archive artifacts - Zero 2
      uses: actions/upload-artifact@v4
      with:
        name: hwdriver2-zero2
        path: HwDriver2/hwdriver2-rpi-zero1

