name: HwDriver2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Build for Raspberry Pi Zero 1
      env:
        GOOS: linux
        GOARCH: arm
        GOARM: 6
      run: go build -v -o hwdriver2-rpi-zero1 cmd/hwdriver2/main.go

    - name: Build for Raspberry Pi Zero 2
      env:
        GOOS: linux
        GOARCH: arm
        GOARM: 7
      run: go build -v -o hwdriver2-rpi-zero2 cmd/hwdriver2/main.go

    # Enable this step once there are some tests written...
    # - name: Run tests
    #   run: go test -v ./...

